language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - make coverage

sudo:
  - required

after_success:
  - COVERALLS_REPO_TOKEN=KT10FVxEm2f2P6EJGONSTE5qgq1LJUloL coveralls
